"""empty message

Revision ID: 004f063330b4
Revises: 0201ea6ed944
Create Date: 2020-07-04 22:18:01.887490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004f063330b4'
down_revision = '0201ea6ed944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), nullable=True))

    op.execute('UPDATE todos SET completed = FALSE WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
